fix reqular hybrid update quality and engine registration validation (#608)
PURPOSE
Regular Hybrid

Fix error when changing viewport render quality while viewport rendering AttributeError: module 'pyrpr' has no attribute 'RENDER_QUALITY_FULL2'.

Added validation for regular Hybrid plugin registration. Creation of empty context causes error -23 on some low-performance GPUs. (i. e. mx460).

NorthStar

Added missing UI element "Texture Compression".
EFFECT OF CHANGE
Fix error when changing viewport render quality while viewport rendering (regression).
Added missing UI element "Texture Compression" (regression).