RPRBLND-1124: Render stamp for tiles. (#466)
PURPOSE
After merging #459 following error occur in non-Win OS:

  File "/Users/user/Library/Application Support/Blender/2.80/scripts/addons/rprblender/utils/render_stamp.py", line 47, in <module>
    class BitmapInfoHeader(ctypes.Structure):
NameError: name 'ctypes' is not defined
EFFECT OF CHANGE
Fix plugin running for non-Windows OS. Due to render stamp