RPRBLND-2268: emission on Grease pencil provides blender crash. (#599)
PURPOSE
In general, the issue is related to the new approach of instances sync (#592)
The issue is that we create pyrpr.Instance from pyrpr.Instance. It's not correct and causes the errors below:

Emission on Grease pencil provides blender crash.
AttributeError: 'Instance' object has no attribute 'poly_count'
EFFECT OF CHANGE
Fixed crash if extruded curve object applied with emission material.
Fixed error 'poly_count' after the final render ends.