RPRBLND-1629: Issue with UDIM tiles. (#185)
PURPOSE
Using UDIM tiles could produce error:
ERROR rpr.init [4913487296]: set_image_gamma() missing 1 required positional argument: 'rpr_context'
Error comes from #181.

EFFECT OF CHANGE
Fixed possible error with UDIM texture.