RPRBLND-1755: Math nodes in materials cause a crash. (#297)
PURPOSE

The scenes below can't be rendered with the message
ValueError: ('Incorrect math operation', 'SMOOTH_MIN')
ValueError: ('Incorrect math operation', 'COMPARE').

EFFECT OF CHANGE

Added support for Compare, Smooth minimum and Smooth maximum operations for Math Node.